services:
  vsixdl:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: melashri/vsixdl
    container_name: vsixdl
    env_file: ../.env
    ports:
      - "5000:5000"
    restart: always
